# FROM node:15 means that you are using the official Node.js Docker image with version 15 as the starting point for building your own Docker image.
# This base image already contains Node.js and related tools, which makes it a good foundation for creating containers that run Node.js applications.
FROM node:15


WORKDIR /app